# Generated by Django 4.2.1 on 2023-10-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_review_delete_productreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
