# Generated by Django 4.2.1 on 2023-10-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_store_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="store",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
    ]
