# Generated by Django 4.2.1 on 2023-10-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0003_alter_store_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="stores/"),
        ),
    ]
