# Generated by Django 4.2.1 on 2023-11-03 00:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0004_store_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="image",
        ),
    ]
