# Generated by Django 4.2.1 on 2023-11-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0005_remove_store_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="stores/"),
        ),
    ]
