# Generated by Django 4.2.1 on 2023-10-02 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
