# Generated by Django 4.2.1 on 2023-12-14 23:57

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_wishlist_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0.0,
                max_digits=2,
                null=True,
                validators=[products.models.validate_rating],
            ),
        ),
    ]
